#+TITLE: vespa-crabro
* Description
  - dirt simple distributed message queues for clojure, built on hornetq

* Usage
  - the client can add [vespa-crabro "0.2.0"] to your project.clj
  - from the jar:
#+BEGIN_EXAMPLE
java -jar vespa-crabro-0.2.0-standalone.jar :host $HOSTNAME :port $PORT
#+END_EXAMPLE
    will generate a .vespa-cookie you can use to connect to the server

  - from the repl:
#+BEGIN_SRC clojure
(def server (create-server))
;=> #'vespa.crabro/server
(cookie server)
;=> ...
(def mb (message-bus))
;=> #'vespa.crabro/mb
(send-to mb "foo" {:a 1 :b 2})
;=> nil
(receive-from mb "foo" println)
;; {:a 1, :b 2}
;=> nil
#+END_SRC
  - the "cookie" is a clojure map of connection parameters.
    create-server will write the cookied to user.home and message-bus
    will read the cookie from there. create-server takes a number of
    options to configure the port and host, etc.

* Todo
** Decompose and Expose
   - give access to hornetq internals
   - make easy ramp up from vespa-crabro to using hornetq api directly
** Split up crabro.clj in to functional units in their own namespaces
** Stomp it up
   - https://github.com/jmesnil/hornetq-stomp/blob/master/src/org/hornetq/stomp/HornetQStompServer.java

* License

Copyright (C) 2011 Kevin Downey

Distributed under the Eclipse Public License, the same as Clojure.
